"""is_correct answer for user

Revision ID: 4b446d0b0289
Revises: 7e8df31e3192
Create Date: 2022-11-04 14:19:22.217582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b446d0b0289'
down_revision = '7e8df31e3192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_users', sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions_users', 'is_correct')
    # ### end Alembic commands ###
