"""current_language users

Revision ID: 7e8df31e3192
Revises: 3f32629acce5
Create Date: 2022-11-03 09:11:42.584590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8df31e3192'
down_revision = '3f32629acce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_language', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_current_language_programming_languages'), 'users', 'programming_languages', ['current_language'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_current_language_programming_languages'), 'users', type_='foreignkey')
    op.drop_column('users', 'current_language')
    # ### end Alembic commands ###
